### ISSUE TITLE
add nbconvert option

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre-client#17]
Add client command to convert a notebook. (Needed by @Athanaseus.) Neater to do it inside the complete environment.
```
jupyter nbconvert --to html --execute notebook.ipynb
```

**Comment by o-smirnov** [comment]
@Athanaseus, this is fixed (just add ``--nbconvert`` to your run-radiopadre invocation) on the ``b1.0pre9`` branch. Please give it a go. Updated 1.0pre9 image should be on dockerhub.

**Comment by Athanaseus** [comment]
Tested the branch, but still getting the same output.

![Screenshot from 2020-03-17 09-17-58](https://user-images.githubusercontent.com/16665629/76831979-113b3300-6831-11ea-99b0-f9030ddabe8c.png)

**Comment by o-smirnov** [comment]
OK @Athanaseus I see the problem, it's not even all that radiopadre-specific. Any notebook that contains images in its cell outputs will have their HREFs propagated into the ``.html`` file as-is. The resulting html file is not self-contained at all. When you load the html file elsewhere, the HREFs don't work anymore (because the images didn't come with the file, and anyway the HREFs were in a funny form specific to that instance of the tornado server).

The solution is to have all the images embedded in the HTML, with ``jupyter nbconvert --to html_embed``. This needs an extra package though, ``jupyter-contrib-nbextensions``.

I have made the changes on the 1.0pre9 branches. However, it now occurs to me that you shouldn't actually need run-radiopadre for this. Could you also re-test your original way of doing it, i.e. directly calling ``jupyter nbconvert --to html_embed --execute notebook.ipynb`` inside the radiopadre venv? The radiopadre kernel is supposed to work standalone too (i.e. without run-radiopadre invoking it), at least well enough to render a notebook... so if it doesn't, it's a bug...

**Comment by Athanaseus** [comment]
Running nbconvert with html embed:

`jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to html_embed --execute std-progress-report.ipynb`
                             
```[NbConvertApp] Converting notebook std-progress-report-Copy1.ipynb to html_embed                                                                                                                                   
[NbConvertApp] Executing notebook with kernel: radiopadre                                                                                                                                                          
[NbConvertApp] try embedding url: http://localhost:1033/0aa83d434abb4677b2ee8ffe3a97ff22/home/ramaila/working/PicA/output0/diagnostic_plots/.radiopadre/thumbs/400.pica-PicA_elevation-tracks_0.png?mtime=158445347
9.7374961, format: 7374961                                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open                                                                                                                                               
    encode_chunked=req.has_header('Transfer-encoding'))                                                                                                                                                            
  File "/usr/lib/python3.6/http/client.py", line 1254, in request                                                                                                                                                  
    self._send_request(method, url, body, headers, encode_chunked)                                                                                                                                                 
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request                                                                                                                                            
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                                                                           
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders                                                                                                                                               
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ramaila/.radiopadre/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 92, in from_notebook_node
    self.replfunc(n)
  File "/home/ramaila/.radiopadre/venv/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 40, in replfunc
    b64_data = base64.b64encode(urlopen(url).read()).decode("utf-8")
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by Athanaseus** [comment]
The first time I tried it timed out, that's why an additional option `--ExecutePreprocessor.timeout=-1`. Default execution timeout is 30 sec.

**Comment by o-smirnov** [comment]
OK... does ``run-radiopadre --nbconvert`` work?

**Comment by Athanaseus** [comment]
Getting the same outcome with:
`$  run-radiopadre ramaila@stills.ru.ac.za:/home/ramaila/working/PicA/output0/std-progress-report-Copy1.ipynb --nbconvert -V`

With singularity, it hangs ...
I will keep an eye if it logs any useful traces.

```
radiopadre.client [0.01s]: Welcome to the radiopadre client!
radiopadre.client [0.01s]:   command line specifies NBCONVERT = True
radiopadre.client: Opening ssh connection to ramaila@stills.ru.ac.za. You may be prompted for your password.
radiopadre.client: Using remote client script within /home/ramaila/.radiopadre/venv
radiopadre.client: running radiopadre client on ramaila@stills.ru.ac.za
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client [0.01s]: Welcome to the radiopadre client!
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Using /usr/bin/singularity for container mode
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Starting new session in container radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Selected ports: 1029:1030:1032:1034:1035:13051:13052:13053:13054:13055
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Session ID/notebook token is 'd8e04a47214a4ac7a1262cef0b55d02d'
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Container name: radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: False std-progress-report-Copy1.ipynb std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Using radiopadre singularity image /home/ramaila/.radiopadre/osmirnov_radiopadre:1.0pre9.singularity.img
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Available notebooks: std-progress-report.ipynb std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Container name: radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: running /usr/bin/singularity instance.start --workdir /home/ramaila/working/PicA/output0 -B /home/ramaila/working/PicA/output0:/home/ramaila/working/PicA/output0 -B /home/ramaila/.radiopadre/.docker-local:/home/ramaila/.local -B /home/ramaila/.radiopadre/sessions/radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb:/home/ramaila/working/PicA/output0/.radiopadre-session -B /home/ramaila/.radiopadre/sessions/radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb:/home/ramaila/.radiopadre/home/ramaila/working/PicA/output0/.radiopadre-session -B /home/ramaila/.radiopadre/.js9-tmp:/.radiopadre/venv/js9-www/tmp /home/ramaila/.radiopadre/osmirnov_radiopadre:1.0pre9.singularity.img radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Running /usr/bin/singularity exec instance://radiopadre-ramaila-fed917a433c344b7b0f1f16a51d6e6cb run-radiopadre --auto-load radiopadre-auto.ipynb --backend venv --browser None --carta-browser --default-notebook radiopadre-default.ipynb --docker-image osmirnov/radiopadre:1.0pre9 --grim-reaper --client-install-repo  --client-install-branch b1.0-pre9 --client-install-pip radiopadre-client --server-install-repo  --server-install-branch b1.0-pre9 --server-install-pip radiopadre --verbose 0 --nbconvert --radiopadre-venv /.radiopadre/venv --inside-container 1029:1030:1032:1034:1035:13051:13052:13053:13054:13055 --workdir /home/ramaila/.radiopadre std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za stderr: WARNING: Removing stale daemon file: /home/ramaila/.singularity/daemon/stills/radiopadre-ramaila-8dfddf93b33449e681fc5a02708f1bed
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   (When using singularity and the image is not yet available locally, this can take a few minutes the first time you run.)
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Waiting for conversion to finish
radiopadre.client: ramaila@stills.ru.ac.za stderr: [NbConvertApp] Converting notebook std-progress-report-Copy1.ipynb to html
radiopadre.client: ramaila@stills.ru.ac.za stderr: [NbConvertApp] Executing notebook with kernel: radiopadre
radiopadre.client: ramaila@stills.ru.ac.za stderr: [NbConvertApp] ERROR | Error while converting 'std-progress-report-Copy1.ipynb'
```

**Comment by o-smirnov** [comment]
Add ``--container-debug`` for more output please.

**Comment by Athanaseus** [comment]
That helped a lot in terms of debugging. That was my bokeh backfiring since it's not installed in the container. Commented it out for now.

This seems to go through BUT it still says `--to html`
```
radiopadre.client [0.01s]: Welcome to the radiopadre client!
radiopadre.client [0.01s]:   command line specifies CONTAINER_DEBUG = True
radiopadre.client [0.01s]:   command line specifies NBCONVERT = True
radiopadre.client: Opening ssh connection to ramaila@stills.ru.ac.za. You may be prompted for your password.
radiopadre.client: Using remote client script within /home/ramaila/.radiopadre/venv
radiopadre.client: running radiopadre client on ramaila@stills.ru.ac.za
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client [0.01s]: Welcome to the radiopadre client!
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Using /usr/bin/singularity for container mode
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Starting new session in container radiopadre-ramaila-f04948509698464baf4b1939709976a9
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Selected ports: 1038:1039:1040:1041:1042:13066:13067:13068:13069:13070
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Session ID/notebook token is '925bdb49124e44eab58e9d0ea3d16b4b'
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Container name: radiopadre-ramaila-f04948509698464baf4b1939709976a9
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: False std-progress-report-Copy1.ipynb std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Using radiopadre singularity image /home/ramaila/.radiopadre/osmirnov_radiopadre:1.0pre9.singularity.img
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Available notebooks: std-progress-report.ipynb std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Container name: radiopadre-ramaila-f04948509698464baf4b1939709976a9
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Running /usr/bin/singularity exec --workdir /home/ramaila/working/PicA/output0 -B /home/ramaila/working/PicA/output0:/home/ramaila/working/PicA/output0 -B /home/ramaila/.radiopadre/.docker-local:/home/ramaila/.local -B /home/ramaila/.radiopadre/sessions/radiopadre-ramaila-f04948509698464baf4b1939709976a9:/home/ramaila/working/PicA/output0/.radiopadre-session -B /home/ramaila/.radiopadre/sessions/radiopadre-ramaila-f04948509698464baf4b1939709976a9:/home/ramaila/.radiopadre/home/ramaila/working/PicA/output0/.radiopadre-session -B /home/ramaila/.radiopadre/.js9-tmp:/.radiopadre/venv/js9-www/tmp /home/ramaila/.radiopadre/osmirnov_radiopadre:1.0pre9.singularity.img run-radiopadre --auto-load radiopadre-auto.ipynb --backend venv --browser None --carta-browser --default-notebook radiopadre-default.ipynb --docker-image osmirnov/radiopadre:1.0pre9 --container-debug --grim-reaper --client-install-repo  --client-install-branch b1.0-pre9 --client-install-pip radiopadre-client --server-install-repo  --server-install-branch b1.0-pre9 --server-install-pip radiopadre --verbose 0 --nbconvert --radiopadre-venv /.radiopadre/venv --inside-container 1038:1039:1040:1041:1042:13066:13067:13068:13069:13070 --workdir /home/ramaila/.radiopadre std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   (When using singularity and the image is not yet available locally, this can take a few minutes the first time you run.)
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Waiting for conversion to finish
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client [0.02s]: Welcome to the radiopadre client!
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: started the radiopadre container
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Inside container, using ports 1038 1039 1040 1041 1042 13066 13067 13068 13069 13070
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: False std-progress-report-Copy1.ipynb std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Running inside radiopadre virtual environment /.radiopadre/venv
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: radiopadre (version 1.0rc9) is installed.
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   Available notebooks: std-progress-report.ipynb std-progress-report-Copy1.ipynb
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Detected radiopadre directory within virtualenv as /radiopadre
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Starting HTTP server process in /home/ramaila/.radiopadre on port 1040
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client:   started as PID 56335
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: **Starting: /.radiopadre/venv/bin/jupyter nbconvert --to html --execute --NotebookApp.token='925bdb49124e44eab58e9d0ea3d16b4b' --NotebookApp.custom_display_url='http://localhost:13066' std-progress-report-Copy1.ipynb in /home/ramaila/working/PicA/output0**
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Waiting for conversion to finish
radiopadre.client: ramaila@stills.ru.ac.za stderr: [NbConvertApp] Converting notebook std-progress-report-Copy1.ipynb to html
radiopadre.client: ramaila@stills.ru.ac.za stderr: [NbConvertApp] Executing notebook with kernel: radiopadre
radiopadre.client: ramaila@stills.ru.ac.za stderr: [NbConvertApp] Writing 358086 bytes to std-progress-report-Copy1.html
radiopadre.client: ramaila@stills.ru.ac.za: radiopadre.client: Terminating remaining child processes (56335)
radiopadre.client: The ssh process to ramaila@stills.ru.ac.za has exited
```

**Comment by Athanaseus** [comment]
PS: Which still leads to the initial problem.

**Comment by o-smirnov** [comment]
Ah hang on, that must be the old container image. Run with ``-u`` (update) to download a new one.

**Comment by Athanaseus** [comment]
Looks like it's re-building but somehow still picks up `--to html`

**Comment by o-smirnov** [comment]
Hmm, ok I just pushed a new image which definitely does html_embed for me... if not for you, we'll figure it out tomorrow.

**Comment by Athanaseus** [comment]
html embed now working, but it still returns connection refused error (above).
I will also try to figure out why this happens.

**Comment by o-smirnov** [comment]
Any updates? Give me the path to your notebook, if stuck.

**Comment by Athanaseus** [comment]
No luck yet...
/home/ramaila/working/PicA/output3/std-progress-report-Copy1.ipynb (stills.ru.ac.za)

**Comment by o-smirnov** [comment]
OK, this works via ``run-radiopadre --nbconvert std-progress-report.ipynb``. I tried it with both the -V and -S back-ends. I did have to remove a cell:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-cde46fe84f63> in <module>
----> 1 plotter1 = figure(x_range=['VLA', 'MeerKAT', 'SRT', 'Plank', 'MWA'],
      2                   y_axis_label="Calibration Error (%)", x_axis_label="Telescope",
      3                   plot_width=800, plot_height=400,
      4                   title="")
      5 

NameError: name 'figure' is not defined
NameError: name 'figure' is not defined
```

...but after that the conversion ran without a hitch.

If you need stuff like boken and whatnot in the notebook, it's trivial to add them to the images and to the virtualenv. Just raise an issue here or on radiopadre.

I confirm that ``jupyter nbconvert`` bombs out with a connection refused. This is something to do with the internal http server not starting right. I will inestigate, keep this issue open.

**Comment by o-smirnov** [comment]
OK I see the problem. ``jupyter nbconvert`` starts up the radiopadre kernel, renders all output, then stops the kernel, and only **then** starts making HTTP requests for embedding images. When running standalone, the internal HTTP server is already gone by then, shut down together with the kernel.

When running via ``run-radiopadre --nbconvert``, it's the client script that stops the server, and only after jupyter nbconvert has exited, so everything works fine.

I don't see an easy fix, and I don't think it's worth making a complicated one, since we have a perfectly functional workaround. @Athanaseus, let's use ``run-radiopadre --nbconvert`` from now on.

**Comment by Athanaseus** [comment]
Yeah no problem, that works perfectly fine since the pipeline will also execute `run-radiopadre --nbconvert` on the host.

> The resulting html file is not self-contained at all. When you load the html file elsewhere, the HREFs don't work anymore 

Just wondering now, to ship the html report will also need the whole output directory (with fits files)?

**Comment by Athanaseus** [comment]
> I did have to remove a cell

Thanks @o-smirnov forgot to get rid of that cell.

> If you need stuff like boken and whatnot in the notebook, it's trivial to add them to the images and to the virtualenv. Just raise an issue here or on radiopadre.

Issue raised https://github.com/ratt-ru/radiopadre/issues/75

**Comment by o-smirnov** [comment]
> Just wondering now, to ship the html report will also need the whole output directory (with fits files)?

No, I think we agreed that the HTML version of the report will be a fixed, static view of the notebook. Images and thumbnails are embedded in the HTML, but all the interactivity is gone, and there are no clickable links. (Which is sort of a necessary condition of the HTML file being standalone, self-contained, and shippable elsewhere -- unless we start playing fancy games with Javascript...)

The full, live, interactive version of the report is only available as a notebook, executed on the host of the output directory via ``run-radiopadre``.

**Comment by Athanaseus** [comment]
Loud and clear. Thanks @o-smirnov

**Comment by Athanaseus** [comment]
@o-smirnov can you please push the latest `osmirnov/radiopadre:1.0pre9` the current one didn't have `bokeh` in.
